[BACKPORT 2024.1][#21811] docdb: fix alma8 fastdebug gcc11 compilation
Summary:
Commit 061dc692f3db28772a8c3fa0a5cad11db1140301 introduces code causing
compilation failure

    ../../src/yb/integration-tests/cdcsdk_ysql_test_base.cc: In member function ‘void yb::cdc::CDCSDKYsqlTest::CheckRecordsConsistencyFromVWAL(const std::vector<yb::cdc::CDCSDKProtoRecordPB>&)’:
    ../../src/yb/integration-tests/cdcsdk_ysql_test_base.cc:3879:9: error: ‘prev_op’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
     3879 |         if (prev_op == RowMessage::DDL) {
          |         ^~
    cc1plus: all warnings being treated as errors

Almalinux 8 + fastdebug + gcc11 is affected, but other build combos such
as those in jenkins_jobs.yml are fine.

Fix the issue by initializing prev_op to UNKNOWN.  This should be fine
according to the logic as far as I can tell.
Jira: DB-10712

Test Plan:
On Almalinux 8:

    ./yb_build.sh fastdebug --gcc11

Close: #21811
Original commit: 193589f61ef5bcdc1f6b61eae052856339b0af3c / D33830

Reviewers: siddharth.shah

Reviewed By: siddharth.shah

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D34494